const site=window.__SITE_DATA__;
const siteUsername=String(site.username||'test');
const siteBase=`/${encodeURIComponent(siteUsername)}`;
const runtimeBase=`/api/runtime/${encodeURIComponent(siteUsername)}`;
const routePath=String(window.__PAGE_PATH__||'').replace(/^\/+|\/+$/g,'');
const isAdminRoute=routePath==='admin';
const isForumRoute=routePath==='forum'||routePath.startsWith('forum/');
const current=site.pages.find(page=>page.path===routePath)||site.pages[0];
const runtimeState={user:null,role:null,registrationMode:'open',accountEnabled:Boolean(site.features?.account),forumPosts:JSON.parse(JSON.stringify(site.forumPosts||[])),registrations:[],joined:false};
const root=document.querySelector('#publishedSite');
try{const liveChannel=new BroadcastChannel('alchemysites-live-preview');liveChannel.addEventListener('message',event=>{if(event.data?.type==='reload')location.reload()});window.addEventListener('beforeunload',()=>liveChannel.close(),{once:true})}catch{}
window.addEventListener('storage',event=>{if(event.key==='alchemysites:published-reload'&&event.newValue)location.reload()});
root.className=`published-site theme-${site.theme}${site.sectionGap?' with-gaps':''}`;
root.style.setProperty('--page-bg',site.background||'#fff');
root.style.background=site.background||'#fff';
root.style.color='var(--page-fg)';
root.innerHTML=isAdminRoute?'<main class="site-admin"><div class="forum-page-loading">正在加载站点后台…</div></main>':isForumRoute?'<main class="forum-page"><div class="forum-page-loading">正在加载社区…</div></main>':current.html||'<div class="empty-canvas"><div><b>这个页面还是空白的</b></div></div>';
document.title=isAdminRoute?`站点后台｜${site.siteName}`:isForumRoute?`社区论坛｜${site.siteName}`:`${current.name}｜${site.siteName}`;

const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function showToast(message){const toast=document.querySelector('#toast');toast.querySelector('span').textContent=message;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,3000)}
function openModal(title,html){document.querySelector('#modalBody').innerHTML=`<h2>${esc(title)}</h2>${html}`;document.querySelector('#previewModal').hidden=false}
function closeModal(){document.querySelector('#previewModal').hidden=true}
function pageUrl(id){const page=site.pages.find(item=>item.id===id);if(!page)return siteBase;return page===site.pages[0]?siteBase:`${siteBase}/${page.path}`}
function forumUrl(path=''){return `${siteBase}/forum${path?`/${encodeURIComponent(path)}`:''}`}
async function api(path,options={}){const request={method:options.method||'GET',headers:{}};if(options.body!==undefined){request.headers['Content-Type']='application/json';request.body=JSON.stringify(options.body)}const response=await fetch(path,request);let data={};try{data=await response.json()}catch{data={error:'服务返回了无法解析的内容'}}if(!response.ok){const error=new Error(data.error||`请求失败（${response.status}）`);error.status=response.status;throw error}return data}
function openLogin(){if(!runtimeState.accountEnabled){showToast('该站点没有启用账号系统');return}const registration=runtimeState.registrationMode==='closed'?'':`<details class="runtime-register"><summary>${runtimeState.registrationMode==='invite'?'使用邀请码创建本站账号':'还没有本站账号？创建一个'}</summary><form class="runtime-form" data-form="register"><label>用户名<input name="username" autocomplete="username" required pattern="[A-Za-z0-9_-]{3,32}" maxlength="32" placeholder="3–32 位字母、数字、_ 或 -"></label><label>密码<input name="password" type="password" autocomplete="new-password" required minlength="8" maxlength="128"></label><label>确认密码<input name="confirmPassword" type="password" autocomplete="new-password" required minlength="8" maxlength="128"></label>${runtimeState.registrationMode==='invite'?'<label>本站邀请码<input name="invite" required pattern="[0-9a-fA-F]{16}" maxlength="16" placeholder="16 位 hex"></label>':''}<button>创建本站账号</button></form></details>`;openModal('站点账号',`<p>这里的账号与其他网站、炼丹社Sites控制台完全独立。</p><form class="runtime-form" data-form="login"><label>用户名<input name="username" autocomplete="username" required maxlength="32" placeholder="输入本站用户名"></label><label>密码<input name="password" type="password" autocomplete="current-password" required minlength="8" maxlength="128" placeholder="输入本站密码"></label><button>登录</button></form>${registration}`)}
function requireLogin(){if(runtimeState.user)return true;openLogin();showToast('请先登录这个网站的独立账号');return false}

function forumAccountMarkup(){return runtimeState.user?`<div class="forum-account"><span>${esc(runtimeState.user.slice(0,1).toUpperCase())}</span><div><small>当前账号</small><b>${esc(runtimeState.user)}</b></div><button data-preview-action="account-logout">退出</button></div>`:`<button class="forum-login" data-preview-action="account-login">登录账号 →</button>`}
function forumShell(content,active='home'){return `<main class="forum-page"><header class="forum-page-header"><button data-preview-action="site-home">← 返回网站</button><a href="${siteBase}/forum"><b>${esc(site.siteName)}</b><span>COMMUNITY / 社区论坛</span></a>${forumAccountMarkup()}</header><div class="forum-layout"><aside><b>社区</b><a class="${active==='home'?'active':''}" href="${siteBase}/forum">全部话题</a><span>AI 研究所</span><span>项目组队</span><span>活动与招新</span><button data-preview-action="forum-compose">＋ 发布话题</button></aside><section class="forum-main">${content}</section></div></main>`}
function forumTopicList(){return runtimeState.forumPosts.map((post,index)=>`<a class="forum-page-topic" href="${forumUrl(post.id)}"><span>${String(index+1).padStart(2,'0')}</span><div><b>${esc(post.title)}</b><p>${esc(post.body)}</p><small>${esc(post.author)} · ${(post.replies||[]).length} 条回复${post.status==='locked'?' · 已锁定':''}</small></div><em>→</em></a>`).join('')||'<div class="forum-empty"><b>还没有话题</b><p>登录后发布第一条讨论。</p></div>'}
function renderForumRoute(){if(!isForumRoute)return;const parts=routePath.split('/');const section=parts[1]||'';
  if(!section){root.innerHTML=forumShell(`<header class="forum-main-head"><div><span>DISCUSSIONS</span><h1>大家都在聊</h1><p>真实保存的话题、回复和活动讨论。</p></div><button data-preview-action="forum-compose">＋ 发布话题</button></header><div class="forum-page-list">${forumTopicList()}</div>`);return}
  if(section==='new'){
    const content=runtimeState.user?`<div class="forum-editor-page"><a href="${siteBase}/forum">← 返回话题列表</a><span>NEW TOPIC</span><h1>发布新话题</h1><p>内容会保存到已发布站点，刷新后仍然存在。</p><form class="forum-page-form" data-form="topic-page"><label>话题标题<input name="title" required maxlength="120" placeholder="用一句话说清楚主题"></label><label>正文<textarea name="body" rows="10" required maxlength="5000" placeholder="补充背景、问题或组队需求……"></textarea></label><button>确认发布</button></form></div>`:`<div class="forum-auth-gate"><a href="${siteBase}/forum">← 返回话题列表</a><span>MEMBER ONLY</span><h1>登录后发布话题</h1><p>论坛使用本站独立账号，登录身份会作为发帖作者保存。</p><button data-preview-action="account-login">登录本站账号 →</button></div>`;root.innerHTML=forumShell(content,'new');return
  }
  const post=runtimeState.forumPosts.find(item=>item.id===decodeURIComponent(section));
  if(!post){root.innerHTML=forumShell(`<div class="forum-auth-gate"><a href="${siteBase}/forum">← 返回话题列表</a><span>404</span><h1>话题不存在</h1><p>它可能已被删除或网址不正确。</p></div>`);document.title=`话题不存在｜${site.siteName}`;return}
  document.title=`${post.title}｜${site.siteName}`;const replies=post.replies||[];const replyBox=post.status==='locked'?'<div class="forum-reply-login"><p>该话题已由管理员锁定，暂不接受新回复。</p></div>':runtimeState.user?`<form class="forum-page-form forum-reply-form" data-form="reply-page" data-post-id="${esc(post.id)}"><label>写下回复<textarea name="body" rows="5" required maxlength="3000" placeholder="认真回应这个话题……"></textarea></label><button>发布回复</button></form>`:`<div class="forum-reply-login"><p>登录后参与讨论</p><button data-preview-action="account-login">登录账号 →</button></div>`;root.innerHTML=forumShell(`<article class="forum-thread-page"><a href="${siteBase}/forum">← 返回话题列表</a><span>TOPIC / ${esc(post.author)}${post.status==='locked'?' / LOCKED':''}</span><h1>${esc(post.title)}</h1><p class="forum-thread-body">${esc(post.body)}</p><div class="forum-replies"><header><b>${replies.length} 条回复</b></header>${replies.map((reply,index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><div><b>${esc(reply.author)}</b><p>${esc(reply.body)}</p></div></article>`).join('')||'<div class="forum-empty"><b>还没有回复</b><p>登录后参与第一条讨论。</p></div>'}</div>${replyBox}</article>`,'thread')
}
function renderForumTopics(){document.querySelectorAll('.forum-content').forEach(container=>{container.querySelector('.block-kicker')?.replaceChildren(document.createTextNode('COMMUNITY / 社区讨论'));container.querySelectorAll('.forum-topic').forEach(item=>item.remove());runtimeState.forumPosts.forEach((post,index)=>container.insertAdjacentHTML('beforeend',`<button class="forum-topic" data-preview-action="forum-thread" data-post-id="${esc(post.id)}"><span>${String(index+1).padStart(2,'0')}</span><b>${esc(post.title)}</b><em>${(post.replies||[]).length} 回复</em></button>`))})}
function renderAccountState(){document.querySelectorAll('.account-panel').forEach(panel=>{const label=esc(panel.dataset.loginLabel||'登录账号');panel.innerHTML=runtimeState.user?`<span class="account-avatar">${esc(runtimeState.user.slice(0,1).toUpperCase())}</span><div><small>${runtimeState.role==='owner'?'站点所有者':'本站账号'}</small><b>${esc(runtimeState.user)}</b></div>${runtimeState.role==='owner'?'<button data-preview-action="site-admin">管理后台</button>':''}<button data-preview-action="account-logout">退出账号</button>`:`<div><small>本站独立账号</small><b>登录或注册</b></div><button data-preview-action="account-login">${label} →</button>`})}
let adminData=null,adminSection='overview',adminLoading=false;
const shortDate=value=>String(value||'').replace('T',' ').slice(0,16);
function adminSectionContent(){
  if(!adminData)return'';
  if(adminSection==='users')return `<section class="admin-panel"><header><span>USERS</span><h2>成员管理</h2><p>管理本站动态账号。站点所有者不能被停用。</p></header><div class="admin-table"><div class="admin-tr admin-th"><span>用户名</span><span>角色</span><span>加入时间</span><span>状态</span><span></span></div>${adminData.users.map(user=>`<div class="admin-tr"><b>${esc(user.username)}</b><span>${user.role==='owner'?'所有者':'成员'}</span><span>${esc(shortDate(user.createdAt))}</span><span class="admin-status ${user.status}">${user.status==='active'?'正常':'已停用'}</span><span>${user.role==='owner'?'—':`<button data-admin-user="${esc(user.username)}" data-next-status="${user.status==='active'?'suspended':'active'}">${user.status==='active'?'停用':'恢复'}</button>`}</span></div>`).join('')}</div></section>`;
  if(adminSection==='access')return `<section class="admin-panel"><header><span>ACCESS</span><h2>注册与访问</h2><p>类似成熟博客平台的成员策略；静态页面仍可公开访问。</p></header><form class="admin-setting-form" data-admin-form="registration"><label>新用户注册策略<select name="registrationMode"><option value="open" ${adminData.registrationMode==='open'?'selected':''}>开放注册</option><option value="invite" ${adminData.registrationMode==='invite'?'selected':''}>仅邀请码注册</option><option value="closed" ${adminData.registrationMode==='closed'?'selected':''}>关闭注册</option></select></label><button>保存策略</button></form><div class="admin-subhead"><div><b>本站邀请码</b><small>16 位 hex · 一次性</small></div><form data-admin-form="invite"><input name="count" type="number" min="1" max="20" value="5"><button>生成邀请码</button></form></div><div class="admin-invites">${adminData.invitations.map(item=>`<div><code>${esc(item.code)}</code><span>${item.status==='available'?'可使用':item.status==='used'?`已由 ${esc(item.usedBy||'成员')} 使用`:'已撤销'}</span>${item.status==='available'?`<button data-admin-copy="${esc(item.code)}">复制</button><button data-admin-revoke="${esc(item.code)}">撤销</button>`:''}</div>`).join('')||'<p>还没有邀请码。</p>'}</div></section>`;
  if(adminSection==='forum')return `<section class="admin-panel"><header><span>MODERATION</span><h2>论坛审核</h2><p>后台只管理动态讨论，不在线修改站点文章。</p></header><div class="admin-forum-list">${adminData.forumPosts.map(post=>`<article><div><small>${esc(post.author)} · ${(post.replies||[]).length} 回复 · ${post.status==='locked'?'已锁定':'开放'}</small><b>${esc(post.title)}</b><p>${esc(post.body)}</p></div><span><button data-admin-forum="${esc(post.id)}" data-forum-action="${post.status==='locked'?'unlock':'lock'}">${post.status==='locked'?'解锁':'锁定'}</button><button class="danger" data-admin-forum="${esc(post.id)}" data-forum-action="delete">删除</button></span></article>`).join('')||'<div class="admin-empty">还没有论坛话题。</div>'}</div></section>`;
  if(adminSection==='system')return `<section class="admin-panel"><header><span>SYSTEM</span><h2>部署与审计</h2><p>内容采用 Hexo 式构建发布，后台只记录版本，不在线编辑文章。</p></header><h3>最近部署</h3><div class="admin-deployments">${adminData.deployments.map(item=>`<div><b>#${item.id} · ${item.pageCount} 页</b><code>${esc(item.hash)}</code><span>${esc(shortDate(item.createdAt))}</span></div>`).join('')}</div><h3>安全与操作日志</h3><div class="admin-audit">${adminData.audit.map(item=>`<div><span>${esc(shortDate(item.createdAt))}</span><b>${esc(item.actor)}</b><code>${esc(item.action)}</code><em>${esc(item.target||'')}</em></div>`).join('')||'<p>暂无日志。</p>'}</div></section>`;
  const stats=adminData.stats;return `<section class="admin-panel"><header><span>DASHBOARD</span><h2>站点概览</h2><p>动态能力集中管理；页面、文章和作品仍从炼丹社Sites控制台构建发布。</p></header><div class="admin-stats"><div><b>${stats.users}</b><span>成员</span></div><div><b>${stats.sessions}</b><span>在线会话</span></div><div><b>${stats.topics}</b><span>论坛话题</span></div><div><b>${stats.replies}</b><span>回复</span></div></div><div class="admin-content-policy"><span>STATIC CONTENT</span><h3>文章不在这里在线编辑</h3><p>站点内容来自版本化构建产物，像 Hexo 一样由控制台重新生成；本站后台只负责账号、社区、权限和运行状态。</p><a href="${siteBase}" target="_blank">查看网站 ↗</a></div><h3>最近部署</h3><div class="admin-deployments">${adminData.deployments.slice(0,5).map(item=>`<div><b>#${item.id} · ${item.pageCount} 页</b><code>${esc(item.hash)}</code><span>${esc(shortDate(item.createdAt))}</span></div>`).join('')}</div></section>`;
}
function renderAdminRoute(){
  if(!runtimeState.user){root.innerHTML=`<main class="admin-auth"><div><span>SITE ADMIN</span><h1>${esc(site.siteName)} 后台</h1><p>使用本站所有者账号登录。这里不接受炼丹社Sites控制台账号。</p><button data-preview-action="account-login">登录站点后台 →</button><a href="${siteBase}">← 返回网站</a></div></main>`;return}
  if(runtimeState.role!=='owner'){root.innerHTML=`<main class="admin-auth"><div><span>403</span><h1>没有后台权限</h1><p>当前账号 ${esc(runtimeState.user)} 是普通成员，只有站点所有者可以进入后台。</p><a href="${siteBase}">← 返回网站</a></div></main>`;return}
  if(!adminData){root.innerHTML='<main class="site-admin"><div class="forum-page-loading">正在读取站点后台…</div></main>';if(!adminLoading)void loadAdminDashboard();return}
  root.innerHTML=`<main class="site-admin"><aside><a class="admin-brand" href="${siteBase}/admin"><span>${esc(site.siteName.slice(0,1))}</span><div><b>${esc(site.siteName)}</b><small>SITE ADMIN</small></div></a><nav>${[['overview','概览','⌂'],['users','成员','人'],['access','注册与访问','钥'],['forum','论坛审核','论'],['system','部署与日志','记']].map(item=>`<button class="${adminSection===item[0]?'active':''}" data-admin-section="${item[0]}"><i>${item[2]}</i>${item[1]}</button>`).join('')}</nav><footer><a href="${siteBase}" target="_blank">查看网站 ↗</a><button data-preview-action="account-logout">退出 ${esc(runtimeState.user)}</button></footer></aside><div class="admin-workspace"><header><div><small>ALCHEMY SITES / MANAGE</small><b>${esc(site.siteName)}</b></div><span>内容只读 · 动态后台</span></header>${adminSectionContent()}</div></main>`;
}
async function loadAdminDashboard(){adminLoading=true;try{adminData=await api(`${runtimeBase}/admin/overview`);renderAdminRoute()}catch(error){if(error.status===401){runtimeState.user=null;renderAdminRoute();openLogin()}else{root.innerHTML=`<main class="admin-auth"><div><span>ERROR</span><h1>后台加载失败</h1><p>${esc(error.message)}</p><a href="${siteBase}">← 返回网站</a></div></main>`}}finally{adminLoading=false}}
function renderRegistrationState(){document.querySelectorAll('[data-preview-action="register"]').forEach(button=>{const registered=runtimeState.registrations.includes(button.dataset.event);button.textContent=registered?'已报名 ✓':'报名活动 →';button.setAttribute('aria-pressed',String(registered))})}
function renderJoinState(){document.querySelectorAll('[data-preview-action="join"]').forEach(button=>{button.textContent=runtimeState.joined?'已经加入 ✓':'现在加入 ↗';button.setAttribute('aria-pressed',String(runtimeState.joined))})}
function renderRuntime(){if(isAdminRoute){renderAdminRoute();return}if(isForumRoute)renderForumRoute();else{renderForumTopics();renderAccountState();renderRegistrationState();renderJoinState()}}
async function loadRuntime(){try{const data=await api(`${runtimeBase}/state`);Object.assign(runtimeState,data);renderRuntime()}catch(error){showToast(`站点服务暂时不可用：${error.message}`)}}
async function toggleRegistration(eventName){if(!requireLogin())return false;const data=await api(`${runtimeBase}/registrations`,{method:'POST',body:{event:eventName}});runtimeState.registrations=data.registrations;renderRegistrationState();showToast(data.registered?`已报名：${eventName}`:`已取消报名：${eventName}`);return true}
async function toggleJoin(){if(!requireLogin())return;const data=await api(`${runtimeBase}/join`,{method:'POST',body:{}});runtimeState.joined=data.joined;renderJoinState();showToast(data.joined?'欢迎加入！你的申请状态已保存。':'已取消加入申请。')}

root.addEventListener('click',event=>{const target=event.target.closest('[data-preview-action]');if(!target)return;event.preventDefault();void handleRootAction(target)});
async function handleRootAction(target){const action=target.dataset.previewAction;try{
  if(action==='navigate'||action==='project'||action==='article'){location.href=pageUrl(target.dataset.pageId);return}
  if(action==='site-home'){location.href=siteBase;return}
  if(action==='forum-compose'){location.href=`${siteBase}/forum/new`;return}
  if(action==='forum-thread'){location.href=forumUrl(target.dataset.postId);return}
  if(action==='account-login'){openLogin();return}
  if(action==='site-admin'){location.href=`${siteBase}/admin`;return}
  if(action==='account-logout'){await api(`${runtimeBase}/logout`,{method:'POST',body:{}});Object.assign(runtimeState,{user:null,role:null,registrations:[],joined:false});adminData=null;renderRuntime();showToast('已退出账号');return}
  if(action==='next-section'){target.closest('section')?.nextElementSibling?.scrollIntoView({behavior:'smooth'});return}
  if(action==='register'){await toggleRegistration(target.dataset.event);return}
  if(action==='join'){await toggleJoin();return}
  if(action==='member'){openModal(target.dataset.title||'成员档案',`<p><b>${esc(target.dataset.role||'社团成员')}</b></p><p>${esc(target.dataset.title||'这位成员')}负责社团的${esc(target.dataset.role||'协作')}工作，也参与每周共创、公开分享和新成员答疑。</p><button class="modal-action" data-modal-action="close">返回成员列表</button>`);return}
  if(action==='gallery'){const index=Number(target.dataset.index||1);openModal(`活动瞬间 0${index}`,`<div class="gallery-detail gallery-detail-${index}" role="img" aria-label="社团活动照片 ${index}"><b>0${index}</b></div><p>${['新成员见面会：从一个想法开始认识彼此。','AI 工作坊：现场完成第一个可运行的小项目。','校园 Hackathon：把草图变成可以演示的作品。','周末分享会：成员轮流讲解最近的探索。'][index-1]||'社团活动记录'}</p><button class="modal-action" data-modal-action="close">返回相册</button>`);return}
  if(action==='notice'){openModal('秋季招新详情','<p><b>9 月 5 日 14:00–18:00</b><br>大学生活动中心 A 区 12 号展位</p><p>现场可以体验 AI 小工具、查看成员作品，并和项目组面对面交流。无需准备作品，欢迎直接来聊。</p><button class="modal-action" data-modal-action="register" data-event="新学期招新">报名这场活动</button>');return}
  if(action==='link'){const url=target.dataset.url||'';if(/^https?:\/\//i.test(url)){location.href=url;return}if(url==='#group'){openModal('加入交流群','<p>在校内通讯工具中搜索群号 <b>AIchemySites-2026</b>，申请备注“姓名 + 学院”。</p><button class="modal-action" data-modal-action="copy" data-copy="AIchemySites-2026">复制群号</button>');return}if(url==='#wechat'){openModal('关注公众号','<p>微信搜索公众号 <b>校园 AI 共创社</b>，获取活动通知与每周项目进展。</p><button class="modal-action" data-modal-action="copy" data-copy="校园 AI 共创社">复制公众号名称</button>');return}showToast('这个链接尚未配置地址')}
}catch(error){if(error.status===401)openLogin();showToast(error.message)}}

root.addEventListener('click',event=>{const target=event.target.closest('[data-admin-section],[data-admin-user],[data-admin-copy],[data-admin-revoke],[data-admin-forum]');if(!target)return;event.preventDefault();void handleAdminAction(target)});
async function refreshAdmin(){adminData=null;renderAdminRoute();await loadAdminDashboard()}
async function handleAdminAction(target){try{
  if(target.dataset.adminSection){adminSection=target.dataset.adminSection;renderAdminRoute();return}
  if(target.dataset.adminCopy){await navigator.clipboard?.writeText(target.dataset.adminCopy);showToast('本站邀请码已复制');return}
  if(target.dataset.adminUser){const next=target.dataset.nextStatus;if(next==='suspended'&&!window.confirm(`确认停用成员 ${target.dataset.adminUser}？其现有会话会退出。`))return;await api(`${runtimeBase}/admin/users/status`,{method:'POST',body:{username:target.dataset.adminUser,status:next}});showToast(next==='active'?'成员已恢复':'成员已停用');await refreshAdmin();return}
  if(target.dataset.adminRevoke){if(!window.confirm(`确认撤销邀请码 ${target.dataset.adminRevoke}？`))return;await api(`${runtimeBase}/admin/invites/revoke`,{method:'POST',body:{code:target.dataset.adminRevoke}});showToast('邀请码已撤销');await refreshAdmin();return}
  if(target.dataset.adminForum){const action=target.dataset.forumAction;if(action==='delete'&&!window.confirm('确认删除这个话题及全部回复？此操作不可恢复。'))return;await api(`${runtimeBase}/admin/forum/moderate`,{method:'POST',body:{postId:target.dataset.adminForum,action}});showToast(action==='delete'?'话题已删除':action==='lock'?'话题已锁定':'话题已解锁');await refreshAdmin()}
}catch(error){showToast(error.message)}}

document.addEventListener('submit',event=>{const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();void submitRuntimeForm(form)});
document.addEventListener('submit',event=>{const form=event.target.closest('[data-admin-form]');if(!form)return;event.preventDefault();void submitAdminForm(form)});
async function submitAdminForm(form){const data=new FormData(form);const button=form.querySelector('button');button.disabled=true;try{if(form.dataset.adminForm==='registration'){await api(`${runtimeBase}/admin/settings`,{method:'POST',body:{registrationMode:String(data.get('registrationMode'))}});showToast('注册策略已保存')}else if(form.dataset.adminForm==='invite'){const payload=await api(`${runtimeBase}/admin/invites/generate`,{method:'POST',body:{count:Number(data.get('count')||1)}});await navigator.clipboard?.writeText((payload.codes||[]).join('\n'));showToast(`已生成 ${payload.codes.length} 个本站邀请码并复制`)}await refreshAdmin()}catch(error){showToast(error.message)}finally{button.disabled=false}}
async function submitRuntimeForm(form){const data=new FormData(form);const button=form.querySelector('button');button.disabled=true;try{
  if(form.dataset.form==='login'){const result=await api(`${runtimeBase}/login`,{method:'POST',body:{username:String(data.get('username')),password:String(data.get('password'))}});runtimeState.user=result.user;closeModal();await loadRuntime();showToast(`已登录：${result.user}`)}
  else if(form.dataset.form==='register'){const password=String(data.get('password')||'');if(password!==String(data.get('confirmPassword')||''))throw new Error('两次输入的密码不一致');const result=await api(`${runtimeBase}/register`,{method:'POST',body:{username:String(data.get('username')),password,invite:String(data.get('invite')||'')}});runtimeState.user=result.user;runtimeState.role=result.role;closeModal();await loadRuntime();showToast(`本站账号 ${result.user} 已创建`)}
  else if(form.dataset.form==='topic-page'){const result=await api(`${runtimeBase}/forum/topics`,{method:'POST',body:{title:String(data.get('title')),body:String(data.get('body'))}});runtimeState.forumPosts=result.forumPosts;location.href=forumUrl(result.forumPosts[0].id)}
  else if(form.dataset.form==='reply-page'){const result=await api(`${runtimeBase}/forum/replies`,{method:'POST',body:{postId:form.dataset.postId,body:String(data.get('body'))}});runtimeState.forumPosts=result.forumPosts;renderForumRoute();showToast('回复已发布并保存')}
}catch(error){if(error.status===401)openLogin();showToast(error.message)}finally{button.disabled=false}}

document.querySelector('#previewModal').addEventListener('click',event=>{const actionButton=event.target.closest('[data-modal-action]');if(actionButton){const action=actionButton.dataset.modalAction;if(action==='close')closeModal();if(action==='register'){void toggleRegistration(actionButton.dataset.event).then(done=>{if(done)closeModal()}).catch(error=>showToast(error.message))}if(action==='copy'){navigator.clipboard?.writeText(actionButton.dataset.copy||'');showToast('已复制')}return}if(event.target.id==='previewModal')closeModal()});
document.querySelector('#closeModalBtn').addEventListener('click',closeModal);
document.querySelector('#toast button').addEventListener('click',()=>document.querySelector('#toast').hidden=true);
renderRuntime();
void loadRuntime();
